# -*- coding: utf-8 -*-
"""EnvioCorreosTraslados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_d4sa_lGUBCrI9njxFK2UusMdO8Yg30
"""

!pip install gspread oauth2client yagmail

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default

# Get credentials for the current user
creds, _ = default()

# Authorize gspread with the credentials
gc = gspread.authorize(creds)

#URL de la hoja
sheet_url = 'https://docs.google.com/spreadsheets/d/1Z3GROl8QC-mbwbW954nL3mdwbq8d-vnzywq_WHBf9cY/edit?gid=1452400004#gid=1452400004'
worksheet = gc.open_by_url(sheet_url).worksheet('TRASLADOS CORREOS')

import yagmail
from getpass import getpass

# Pide la contraseña de forma segura
contraseña = getpass('Ingresa tu contraseña de Gmail: ')

# Crear conexión SMTP con configuración explícita
yag = yagmail.SMTP(
    user='correo .com',
    password=contraseña,
    host='smtp.gmail.com',
    port=587,
    smtp_starttls=True,
    smtp_ssl=False
)

#leer datos del sheet
data = worksheet.get_all_records()

# Lista de destinatarios
destinatarios = ['angie.sosa@segurosbolivar.com']

yag.send(
    to='correo .com',
    subject='Prueba de envío automático',
    contents='Hola, este es un mensaje de prueba enviado desde Google Colab.'
)
print("Correo enviado correctamente.")

# Leer todos los registros de la hoja
data = worksheet.get_all_records()

# Mostrar cuántas filas encontró
print(f"Se encontraron {len(data)} registros.")

# Mostrar los primeros 2 registros como ejemplo
for fila in data[:2]:
    print(fila)

#Envio de correo individual por empresa
for i, fila in enumerate(data):
  if fila.get('CORREO ENVIADO', '').strip().lower() == 'SI':
    continue

  empresa = fila['EMPRESA']
  nit = fila['NIT']
  poliza = fila['POLIZA']
  numeroCaso = fila['NUMERO CASO']
  fechaRadicado = fila['FECHA RADICADO']
  fechaSolicitada = fila['FECHA SOLICITADA']
  localidad = fila['LOCALIDAD']
  canal = fila['CANAL']
  canalComercial = fila['CANAL COMERCIAL']
  asesor = fila['ASESOR']
  pygGlobal = fila['P&G GLOBAL']
  ultimoAporte = fila['ULTIMO APORTE']

  asunto = f'Traslado ARL Póliza {poliza} - NIT {nit} - {empresa} - CASO {numeroCaso}'
  cuerpo = f"""
  Nos permitimos informar que el día {fechaRadicado} fue radicada la solicitud de traslado de la empresa {empresa} con NIT {nit} y Póliza {poliza} para surtir efecto a partir del {fechaSolicitada}

  Localidad: {localidad}
  Canal: {canal}
  Canal Comercial: {canalComercial}
  Asesor A y C: {asesor}
  P&G Global: {pygGlobal}
  Último Aporte: {ultimoAporte}


  """

  yag.send(to=destinatarios, subject=asunto, contents=cuerpo)

  #marcar como enviado (marcar 'si' en la columna correo enviado)
  worksheet.update_cell(i + 2, 13, 'SI')


print('Correo enviado exitosamente')
